version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis_dev
    ports:
      - '6379:6379'

  app:
    build:
      context: .
      args:
        REDIS_URL: ${REDIS_URL}
    container_name: taskhub_app_dev
    ports:
      - '3000:3000'
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
