services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'

  app:
    build:
      context: .
      args:
        REDIS_URL: ${REDIS_URL}
    container_name: taskhub_app
    ports:
      - '3000:3000'
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - /app/node_modules
