const avatarBase =
  'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-';

export const users = [
  { id: 'u1', name: 'Alice Johnson', avatarUrl: `${avatarBase}1.png` },
  { id: 'u2', name: 'Bob Smith', avatarUrl: `${avatarBase}2.png` },
  { id: 'u3', name: 'Charlie Brown', avatarUrl: `${avatarBase}3.png` },
  { id: 'u4', name: 'Diana Prince', avatarUrl: `${avatarBase}4.png` },
  { id: 'u5', name: 'Ethan Clark', avatarUrl: `${avatarBase}5.png` },
  { id: 'u6', name: 'Fiona White', avatarUrl: `${avatarBase}6.png` },
  { id: 'u7', name: 'George Hall', avatarUrl: `${avatarBase}7.png` },
  { id: 'u8', name: 'Hannah Lee', avatarUrl: `${avatarBase}8.png` },
  { id: 'u9', name: 'Ivan Petrov', avatarUrl: `${avatarBase}9.png` },
  { id: 'u10', name: 'Julia Schmidt', avatarUrl: `${avatarBase}10.png` },
];

export const projects = [
  {
    id: 't1',
    title: 'Design UI',
    status: 'pending',
    progress: 0,
    dueDate: new Date('2025-07-10'),
    icon: 'Plane',
    tasks: [],
  },
  {
    id: 't2',
    title: 'Set up database',
    status: 'in progress',
    progress: 25,
    dueDate: new Date('2025-07-12'),
    icon: 'Plane',
    tasks: [],
  },
  {
    id: 't3',
    title: 'Implement authentication',
    status: 'done',
    progress: 100,
    dueDate: new Date('2025-07-05'),
    icon: 'Plane',
    tasks: [
      { id: 'st1', title: 'Design login screen' },
      { id: 'st2', title: 'Create backend endpoint' },
      { id: 'st3', title: 'Test authentication flow' },
    ],
  },
  {
    id: 't4',
    title: 'Write documentation',
    status: 'in progress',
    progress: 40,
    dueDate: new Date('2025-07-08'),
    icon: 'Plane',
    tasks: [],
  },
  {
    id: 't5',
    title: 'Create unit tests',
    status: 'pending',
    progress: 0,
    dueDate: new Date('2025-07-14'),
    icon: 'Plane',
    tasks: [],
  },
  {
    id: 't6',
    title: 'Deploy to staging',
    status: 'in progress',
    progress: 60,
    dueDate: new Date('2025-07-15'),
    icon: 'Plane',
    tasks: [
      { id: 'st4', title: 'Build release version' },
      { id: 'st5', title: 'Upload to server' },
      { id: 'st6', title: 'Smoke test deployment' },
    ],
  },
  {
    id: 't7',
    title: 'Fix reported bugs',
    status: 'in progress',
    progress: 75,
    dueDate: new Date('2025-07-16'),
    icon: 'Plane',
    tasks: [],
  },
  {
    id: 't8',
    title: 'Code review',
    status: 'done',
    progress: 100,
    dueDate: new Date('2025-07-07'),
    icon: 'Plane',
    tasks: [],
  },
  {
    id: 't9',
    title: 'Refactor modules',
    status: 'in progress',
    progress: 50,
    dueDate: new Date('2025-07-20'),
    icon: 'PlaneIcon',
    tasks: [
      { id: 'st7', title: 'Clean up old code' },
      { id: 'st8', title: 'Extract reusable components' },
      { id: 'st9', title: 'Improve typing' },
    ],
  },
];
